### ISSUE TITLE
No module named dee.application 

### ISSUE THREAD

**Issue by raimund24** [MicahCarrick/desktop-entry-editor#5]
Starting desktop-entry-editor doesn't work, instead I get the message "No module named dee.application".

Version of desktop-entry-editor:
The problem occurs with prepacked desktop-entry-editor-0.1.0.tar.gz, desktop-entry-editor-0.1.1.tar.gz and current git trunk as well (Revision 3a45e0d Dez 27 2011)

System-Info:

```
$ uname -a
Linux raimund1 3.0.0-16-generic #28-Ubuntu SMP Fri Jan 27 17:44:39 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=11.10
DISTRIB_CODENAME=oneiric
DISTRIB_DESCRIPTION="Ubuntu 11.10"
```

Commands used to install:

```
sudo apt-get install libgtk-3-0 python-gobject libgtksourceview-3.0 python-xdg libglib2.0-dev autotools-dev m4 gettext intltool
cd /tmp
git clone https://github.com/Quixotix/desktop-entry-editor.git
cd desktop-entry-editor
aclocal -I m4
intltoolize
autoconf
automake --add-missing
./configure
make
sudo make install
```

**Comment by akinevz2** [comment]
Building on Ubuntu 25.04 results in `No module named 'dee'`

**Comment by akinevz2** [comment]
@MicahCarrick @JanrainMicah possible to reopen issue?

**Comment by akinevz2** [comment]
Note for those that might come here looking for an alternative, gnome ships with a version of: https://flathub.org/apps/page.codeberg.libre_menu_editor.LibreMenuEditor
