### ISSUE TITLE
gtk-builder-error-quark: Invalid property: GtkGrid.n_rows on line 79 (11)

### ISSUE THREAD

**Issue by kc97ble** [MicahCarrick/desktop-entry-editor#7]
After installing the app, I used Terminal to launch it, then got this message:

gtk-builder-error-quark: Invalid property: GtkGrid.n_rows on line 79 (11)

Therefore, I can't launch the app.

**Comment by lowy** [comment]
me too

**Comment by MicahCarrick** [comment]
Fixed in v1.1.2

**Comment by kc97ble** [comment]
Interesting! Finally it is fixed after 3.5 years.
